#include <http_utils.h>
#include <string.h>

int handle_homepage(HTTPServerConnection* conn, const char* query) {

    const char* html =
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "<meta charset=\"UTF-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, "
        "initial-scale=1.0\">"
        "<title>Just Api</title>"
        "<style>"
        "  @import "
        "url('https://fonts.googleapis.com/"
        "css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300&family=Syne:"
        "wght@400;500;600;700;800&display=swap');"
        "  :root {"
        "    --bg: #0a0a0b;"
        "    --surface: #111113;"
        "    --surface2: #18181c;"
        "    --border: #222226;"
        "    --border2: #2e2e35;"
        "    --text: #e8e8ec;"
        "    --muted: #6b6b7a;"
        "    --accent: #4fffb0;"
        "    --accent2: #00d4ff;"
        "    --warn: #ff8c42;"
        "    --get: #4fffb0;"
        "    --post: #f7c948;"
        "  }"
        "  * { box-sizing: border-box; margin: 0; padding: 0; }"
        "  html { scroll-behavior: smooth; }"
        "  body {"
        "    background: var(--bg);"
        "    color: var(--text);"
        "    font-family: 'DM Mono', monospace;"
        "    font-size: 13px;"
        "    line-height: 1.6;"
        "    min-height: 100vh;"
        "  }"
        "  .grid-bg {"
        "    position: fixed; inset: 0; z-index: 0;"
        "    background-image: linear-gradient(var(--border) 1px, transparent "
        "1px), linear-gradient(90deg, var(--border) 1px, transparent 1px);"
        "    background-size: 40px 40px;"
        "    opacity: 0.35;"
        "    pointer-events: none;"
        "  }"
        "  .container { max-width: 900px; margin: 0 auto; padding: 60px 24px; "
        "position: relative; z-index: 1; }"
        "  header { margin-bottom: 64px; }"
        "  .badge {"
        "    display: inline-block; font-size: 10px; font-weight: 500; "
        "letter-spacing: 0.12em; text-transform: uppercase;"
        "    color: var(--accent); border: 1px solid var(--accent); padding: "
        "3px 10px; border-radius: 2px;"
        "    margin-bottom: 20px; font-family: 'DM Mono', monospace;"
        "  }"
        "  h1 { font-family: 'Syne', sans-serif; font-size: clamp(36px, 6vw, "
        "64px); font-weight: 800; letter-spacing: -0.03em; line-height: 1; "
        "color: var(--text); margin-bottom: 16px; }"
        "  h1 span { color: var(--accent); }"
        "  .subtitle { color: var(--muted); font-size: 13px; max-width: 480px; "
        "line-height: 1.7; }"
        "  .subtitle a { color: var(--accent2); text-decoration: none; "
        "border-bottom: 1px solid currentColor; padding-bottom: 1px; }"
        "  .subtitle a:hover { opacity: 0.75; }"
        "  .section-label {"
        "    font-size: 10px; letter-spacing: 0.15em; text-transform: "
        "uppercase;"
        "    color: var(--muted); margin-bottom: 16px; margin-top: 48px;"
        "    display: flex; align-items: center; gap: 12px;"
        "  }"
        "  .section-label::after { content: ''; flex: 1; height: 1px; "
        "background: var(--border); }"
        "  .endpoints { display: flex; flex-direction: column; gap: 2px; }"
        "  .endpoint {"
        "    border: 1px solid var(--border);"
        "    border-radius: 4px;"
        "    overflow: hidden;"
        "    transition: border-color 0.15s;"
        "  }"
        "  .endpoint:hover { border-color: var(--border2); }"
        "  .ep-header {"
        "    display: flex; align-items: center; gap: 12px;"
        "    padding: 14px 16px; cursor: pointer; user-select: none;"
        "    background: var(--surface);"
        "  }"
        "  .ep-header:hover { background: var(--surface2); }"
        "  .method {"
        "    font-size: 10px; font-weight: 500; letter-spacing: 0.08em;"
        "    padding: 2px 7px; border-radius: 2px; flex-shrink: 0; "
        "font-family: 'DM Mono', monospace;"
        "  }"
        "  .method.get { background: rgba(79,255,176,0.12); color: var(--get); "
        "border: 1px solid rgba(79,255,176,0.25); }"
        "  .method.post { background: rgba(247,201,72,0.12); color: "
        "var(--post); border: 1px solid rgba(247,201,72,0.25); }"
        "  .ep-path { color: var(--text); font-size: 13px; flex: 1; }"
        "  .ep-desc { color: var(--muted); font-size: 12px; text-align: right; "
        "flex-shrink: 0; }"
        "  .ep-arrow { color: var(--muted); font-size: 10px; transition: "
        "transform 0.2s; flex-shrink: 0; }"
        "  .ep-body {"
        "    display: none; border-top: 1px solid var(--border);"
        "    background: var(--bg); padding: 20px 16px 16px;"
        "  }"
        "  .ep-body.open { display: block; }"
        "  .ep-arrow.open { transform: rotate(180deg); }"
        "  .params-title { font-size: 10px; letter-spacing: 0.1em; "
        "text-transform: uppercase; color: var(--muted); margin-bottom: 10px; }"
        "  .param-row { display: flex; gap: 12px; align-items: baseline; "
        "margin-bottom: 6px; }"
        "  .param-name { color: var(--accent2); min-width: 90px; flex-shrink: "
        "0; }"
        "  .param-req { font-size: 10px; color: var(--warn); min-width: 48px; "
        "flex-shrink: 0; }"
        "  .param-opt { font-size: 10px; color: var(--muted); min-width: 48px; "
        "flex-shrink: 0; }"
        "  .param-desc { color: var(--muted); font-size: 12px; }"
        "  .example-url {"
        "    margin-top: 14px; padding: 10px 14px;"
        "    background: var(--surface2); border: 1px solid var(--border);"
        "    border-radius: 3px; color: var(--muted); font-size: 12px;"
        "    display: flex; align-items: center; justify-content: "
        "space-between; gap: 12px; flex-wrap: wrap;"
        "  }"
        "  .example-url code { color: var(--text); word-break: break-all; }"
        "  .try-btn {"
        "    flex-shrink: 0; padding: 5px 14px; font-size: 11px; font-family: "
        "'DM Mono', monospace;"
        "    background: transparent; border: 1px solid var(--accent); color: "
        "var(--accent);"
        "    border-radius: 2px; cursor: pointer; letter-spacing: 0.05em; "
        "transition: all 0.15s;"
        "  }"
        "  .try-btn:hover { background: var(--accent); color: var(--bg); }"
        "  .try-btn:disabled { opacity: 0.4; cursor: default; }"
        "  .response-box {"
        "    margin-top: 10px; border: 1px solid var(--border); border-radius: "
        "3px; overflow: hidden; display: none;"
        "  }"
        "  .response-box.visible { display: block; }"
        "  .response-header { background: var(--surface2); padding: 6px 14px; "
        "font-size: 10px; letter-spacing: 0.08em; text-transform: uppercase; "
        "color: var(--muted); display: flex; align-items: center; "
        "justify-content: space-between; }"
        "  .status-badge { font-size: 11px; padding: 2px 8px; border-radius: "
        "2px; }"
        "  .status-ok { background: rgba(79,255,176,0.12); color: var(--get); }"
        "  .status-err { background: rgba(255,80,80,0.12); color: #ff5555; }"
        "  .response-body { padding: 14px; max-height: 280px; overflow-y: "
        "auto; font-size: 12px; line-height: 1.6; color: #aaa; white-space: "
        "pre; overflow-x: auto; }"
        "  .loading { color: var(--muted); font-style: italic; }"
        "  footer { margin-top: 80px; padding-top: 24px; border-top: 1px solid "
        "var(--border); display: flex; align-items: center; justify-content: "
        "space-between; color: var(--muted); font-size: 11px; }"
        "  footer a { color: var(--muted); text-decoration: none; "
        "border-bottom: 1px solid var(--border2); padding-bottom: 1px; }"
        "  footer a:hover { color: var(--text); }"
        "  @media (max-width: 600px) { .ep-desc { display: none; } .param-row "
        "{ flex-wrap: wrap; } }"
        "</style>"
        "</head>"
        "<body>"
        "<div class=\"grid-bg\"></div>"
        "<div class=\"container\">"
        "  <header>"
        "    <div class=\"badge\">REST API</div>"
        "    <h1>Just <span>Api</span></h1>"
        "    <p class=\"subtitle\">A lightweight HTTP API for weather data, "
        "electricity prices, and energy planning. "
        "    Source on <a "
        "href=\"https://github.com/Stockholm-3/just-api\" "
        "target=\"_blank\">GitHub</a>.</p>"
        "  </header>"

        "  <div class=\"section-label\">Utility</div>"
        "  <div class=\"endpoints\">"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/health</span>"
        "        <span class=\"ep-desc\">Server health check</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <p style=\"color:var(--muted);font-size:12px\">None</p>"
        "        <div class=\"example-url\"><code>GET /health</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/health')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/echo</span>"
        "        <span class=\"ep-desc\">Echo raw request</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <p style=\"color:var(--muted);font-size:12px\">None &mdash; "
        "returns the raw request back to the client.</p>"
        "        <div class=\"example-url\"><code>GET /echo</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/echo')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "  </div>"

        "  <div class=\"section-label\">Weather</div>"
        "  <div class=\"endpoints\">"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/current</span>"
        "        <span class=\"ep-desc\">Current conditions by "
        "coordinates</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lat</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Latitude (decimal degrees)</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lon</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Longitude (decimal degrees)</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/current?lat=59.3293&amp;lon=18.0686</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/current?lat=59.3293&lon=18.0686')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/weather</span>"
        "        <span class=\"ep-desc\">Current conditions by city name</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">city</span><span "
        "class=\"param-req\">required</span><span class=\"param-desc\">City "
        "name</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">country</span><span "
        "class=\"param-opt\">optional</span><span class=\"param-desc\">ISO "
        "country code (e.g. SE)</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">region</span><span "
        "class=\"param-opt\">optional</span><span "
        "class=\"param-desc\">Region/state name to narrow results</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/weather?city=Stockholm&amp;country=SE</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/weather?city=Stockholm&country=SE')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/hourly</span>"
        "        <span class=\"ep-desc\">Hourly forecast</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters (coordinates mode)</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lat</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Latitude</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lon</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Longitude</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">hours</span><span "
        "class=\"param-opt\">optional</span><span "
        "class=\"param-desc\">Forecast window in hours (default 24, max "
        "168)</span></div>"
        "        <p class=\"params-title\" "
        "style=\"margin-top:12px\">Parameters (city mode)</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">city</span><span "
        "class=\"param-req\">required</span><span class=\"param-desc\">City "
        "name</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">country</span><span "
        "class=\"param-opt\">optional</span><span class=\"param-desc\">ISO "
        "country code</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">hours</span><span "
        "class=\"param-opt\">optional</span><span "
        "class=\"param-desc\">Forecast window in hours (default 24, max "
        "168)</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/hourly?lat=59.3293&amp;lon=18.0686&amp;hours=24</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/hourly?lat=59.3293&lon=18.0686&hours=24')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/minutely</span>"
        "        <span class=\"ep-desc\">15-minute interval forecast</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters (coordinates mode)</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lat</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Latitude</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lon</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Longitude</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">hours</span><span "
        "class=\"param-opt\">optional</span><span "
        "class=\"param-desc\">Forecast window in hours (default 24, max "
        "168)</span></div>"
        "        <p class=\"params-title\" "
        "style=\"margin-top:12px\">Parameters (city mode)</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">city</span><span "
        "class=\"param-req\">required</span><span class=\"param-desc\">City "
        "name</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">country</span><span "
        "class=\"param-opt\">optional</span><span class=\"param-desc\">ISO "
        "country code</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">hours</span><span "
        "class=\"param-opt\">optional</span><span "
        "class=\"param-desc\">Forecast window in hours (default 24, max "
        "168)</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/minutely?lat=59.3293&amp;lon=18.0686&amp;hours=6</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/minutely?lat=59.3293&lon=18.0686&hours=6')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/forecast</span>"
        "        <span class=\"ep-desc\">General forecast (alias)</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lat</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Latitude</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">lon</span><span "
        "class=\"param-req\">required</span><span "
        "class=\"param-desc\">Longitude</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">hours</span><span "
        "class=\"param-opt\">optional</span><span "
        "class=\"param-desc\">Forecast window in hours (default "
        "24)</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/forecast?lat=59.3293&amp;lon=18.0686</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/forecast?lat=59.3293&lon=18.0686')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/cities</span>"
        "        <span class=\"ep-desc\">City autocomplete search</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">query</span><span "
        "class=\"param-req\">required</span><span class=\"param-desc\">Partial "
        "or full city name (min 2 characters)</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/cities?query=Stock</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/cities?query=Stock')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "  </div>"

        "  <div class=\"section-label\">Electricity</div>"
        "  <div class=\"endpoints\">"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/elpris</span>"
        "        <span class=\"ep-desc\">Swedish electricity spot prices</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">price</span><span "
        "class=\"param-req\">required</span><span class=\"param-desc\">Price "
        "zone: SE1, SE2, SE3, or SE4</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">date</span><span "
        "class=\"param-opt\">optional</span><span class=\"param-desc\">Date in "
        "YYYY-MM-DD format. Omit for latest prices.</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/elpris?price=SE3</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/elpris?price=SE3')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "    <div class=\"endpoint\">"
        "      <div class=\"ep-header\" onclick=\"toggle(this)\">"
        "        <span class=\"method get\">GET</span>"
        "        <span class=\"ep-path\">/v1/get_plan</span>"
        "        <span class=\"ep-desc\">Energy plan for a city</span>"
        "        <span class=\"ep-arrow\">&#9650;</span>"
        "      </div>"
        "      <div class=\"ep-body\">"
        "        <p class=\"params-title\">Parameters</p>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">city</span><span "
        "class=\"param-req\">required</span><span class=\"param-desc\">Swedish "
        "city name</span></div>"
        "        <div class=\"param-row\"><span "
        "class=\"param-name\">price</span><span "
        "class=\"param-req\">required</span><span class=\"param-desc\">Price "
        "zone: SE1, SE2, SE3, or SE4</span></div>"
        "        <div class=\"example-url\"><code>GET "
        "/v1/get_plan?city=Stockholm&amp;price=SE3</code>"
        "          <button class=\"try-btn\" onclick=\"tryIt(this, "
        "'/v1/get_plan?city=Stockholm&price=SE3')\">Try it</button>"
        "        </div>"
        "        <div class=\"response-box\"><div "
        "class=\"response-header\">Response <span "
        "class=\"status-badge\"></span></div><pre "
        "class=\"response-body\"></pre></div>"
        "      </div>"
        "    </div>"
        "  </div>"

        "  <footer>"
        "    <span>Just API</span>"
        "    <a href=\"https://github.com/Stockholm-3/just-api\" "
        "target=\"_blank\">GitHub</a>"
        "  </footer>"
        "</div>"

        "<script>"
        "function toggle(header) {"
        "  var body = header.nextElementSibling;"
        "  var arrow = header.querySelector('.ep-arrow');"
        "  var open = body.classList.toggle('open');"
        "  if (open) { arrow.classList.add('open'); } else { "
        "arrow.classList.remove('open'); }"
        "}"
        "function tryIt(btn, url) {"
        "  var epBody = btn.closest('.ep-body');"
        "  var box = epBody.querySelector('.response-box');"
        "  var pre = box.querySelector('.response-body');"
        "  var badge = box.querySelector('.status-badge');"
        "  box.classList.add('visible');"
        "  pre.textContent = 'Loading...';"
        "  pre.className = 'response-body loading';"
        "  badge.textContent = '';"
        "  badge.className = 'status-badge';"
        "  btn.disabled = true;"
        "  fetch(url)"
        "    .then(function(r) {"
        "      var status = r.status;"
        "      var ct = r.headers.get('content-type') || '';"
        "      badge.textContent = status;"
        "      badge.className = 'status-badge ' + (status >= 200 && status < "
        "300 ? 'status-ok' : 'status-err');"
        "      if (ct.indexOf('json') !== -1) {"
        "        return r.json().then(function(d) { return JSON.stringify(d, "
        "null, 2); });"
        "      } else {"
        "        return r.text();"
        "      }"
        "    })"
        "    .then(function(text) {"
        "      pre.textContent = text;"
        "      pre.className = 'response-body';"
        "    })"
        "    .catch(function(e) {"
        "      pre.textContent = 'Request failed: ' + e.message;"
        "      pre.className = 'response-body';"
        "      badge.textContent = 'ERR';"
        "      badge.className = 'status-badge status-err';"
        "    })"
        "    .finally(function() { btn.disabled = false; });"
        "}"
        "</script>"
        "</body></html>";

    return send_response(conn, 200, "text/html", html, strlen(html));
}
